# Generated by Django 4.2.6 on 2023-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_user_user_id_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(default=123, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
