# Generated by Django 4.2.6 on 2023-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_username_user_user_name_user_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0, max_length=50)),
                ('lng', models.FloatField(default=0.0, max_length=50)),
                ('accident_probability', models.FloatField(default=0.0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0, max_length=50)),
                ('lng', models.FloatField(default=0.0, max_length=50)),
                ('route', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('establishment', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
