# Generated by Django 4.2.6 on 2023-11-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_routeaddress_city_alter_routeaddress_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentprobability',
            name='road_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
